/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSaveRouteImport } from './routes/_app/save'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppPodcastsIndexRouteImport } from './routes/_app/podcasts/index'
import { Route as AppArticlesIndexRouteImport } from './routes/_app/articles/index'
import { Route as AppPodcastIdRouteImport } from './routes/_app/podcast.$id'
import { Route as AppArticleIdRouteImport } from './routes/_app/article.$id'
import { Route as AppSaveTitleUrlRouteImport } from './routes/_app/save.$title.$url'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSaveRoute = AppSaveRouteImport.update({
  id: '/save',
  path: '/save',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppPodcastsIndexRoute = AppPodcastsIndexRouteImport.update({
  id: '/podcasts/',
  path: '/podcasts/',
  getParentRoute: () => AppRoute,
} as any)
const AppArticlesIndexRoute = AppArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => AppRoute,
} as any)
const AppPodcastIdRoute = AppPodcastIdRouteImport.update({
  id: '/podcast/$id',
  path: '/podcast/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppArticleIdRoute = AppArticleIdRouteImport.update({
  id: '/article/$id',
  path: '/article/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSaveTitleUrlRoute = AppSaveTitleUrlRouteImport.update({
  id: '/$title/$url',
  path: '/$title/$url',
  getParentRoute: () => AppSaveRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof AppDashboardRoute
  '/save': typeof AppSaveRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/': typeof AuthIndexRoute
  '/article/$id': typeof AppArticleIdRoute
  '/podcast/$id': typeof AppPodcastIdRoute
  '/articles': typeof AppArticlesIndexRoute
  '/podcasts': typeof AppPodcastsIndexRoute
  '/save/$title/$url': typeof AppSaveTitleUrlRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof AppDashboardRoute
  '/save': typeof AppSaveRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/': typeof AuthIndexRoute
  '/article/$id': typeof AppArticleIdRoute
  '/podcast/$id': typeof AppPodcastIdRoute
  '/articles': typeof AppArticlesIndexRoute
  '/podcasts': typeof AppPodcastsIndexRoute
  '/save/$title/$url': typeof AppSaveTitleUrlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/save': typeof AppSaveRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/': typeof AuthIndexRoute
  '/_app/article/$id': typeof AppArticleIdRoute
  '/_app/podcast/$id': typeof AppPodcastIdRoute
  '/_app/articles/': typeof AppArticlesIndexRoute
  '/_app/podcasts/': typeof AppPodcastsIndexRoute
  '/_app/save/$title/$url': typeof AppSaveTitleUrlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/save'
    | '/login'
    | '/'
    | '/article/$id'
    | '/podcast/$id'
    | '/articles'
    | '/podcasts'
    | '/save/$title/$url'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/save'
    | '/login'
    | '/'
    | '/article/$id'
    | '/podcast/$id'
    | '/articles'
    | '/podcasts'
    | '/save/$title/$url'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/dashboard'
    | '/_app/save'
    | '/_auth/login'
    | '/_auth/'
    | '/_app/article/$id'
    | '/_app/podcast/$id'
    | '/_app/articles/'
    | '/_app/podcasts/'
    | '/_app/save/$title/$url'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_app/save': {
      id: '/_app/save'
      path: '/save'
      fullPath: '/save'
      preLoaderRoute: typeof AppSaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/podcasts/': {
      id: '/_app/podcasts/'
      path: '/podcasts'
      fullPath: '/podcasts'
      preLoaderRoute: typeof AppPodcastsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/articles/': {
      id: '/_app/articles/'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof AppArticlesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/podcast/$id': {
      id: '/_app/podcast/$id'
      path: '/podcast/$id'
      fullPath: '/podcast/$id'
      preLoaderRoute: typeof AppPodcastIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/article/$id': {
      id: '/_app/article/$id'
      path: '/article/$id'
      fullPath: '/article/$id'
      preLoaderRoute: typeof AppArticleIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/save/$title/$url': {
      id: '/_app/save/$title/$url'
      path: '/$title/$url'
      fullPath: '/save/$title/$url'
      preLoaderRoute: typeof AppSaveTitleUrlRouteImport
      parentRoute: typeof AppSaveRoute
    }
  }
}

interface AppSaveRouteChildren {
  AppSaveTitleUrlRoute: typeof AppSaveTitleUrlRoute
}

const AppSaveRouteChildren: AppSaveRouteChildren = {
  AppSaveTitleUrlRoute: AppSaveTitleUrlRoute,
}

const AppSaveRouteWithChildren =
  AppSaveRoute._addFileChildren(AppSaveRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppSaveRoute: typeof AppSaveRouteWithChildren
  AppArticleIdRoute: typeof AppArticleIdRoute
  AppPodcastIdRoute: typeof AppPodcastIdRoute
  AppArticlesIndexRoute: typeof AppArticlesIndexRoute
  AppPodcastsIndexRoute: typeof AppPodcastsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppSaveRoute: AppSaveRouteWithChildren,
  AppArticleIdRoute: AppArticleIdRoute,
  AppPodcastIdRoute: AppPodcastIdRoute,
  AppArticlesIndexRoute: AppArticlesIndexRoute,
  AppPodcastsIndexRoute: AppPodcastsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
